### ISSUE TITLE
loading css from file

### ISSUE THREAD

**Issue by richyrb00** [JSCasts-episodes/ep14-ssr-with-react-and-express#2]
I've got a css file with some global styling that i would like to load from the string inside layout.js 

but i'm unsure of where the css should be placed? 

layout.js is imported into app-controller. which is then imported into app.. 

so should it be on the same folder branch as app or should it be inside frontend folder?

**Comment by wojtek-krysiak** [comment]
I would create "/public" folder inside the app and put file there, then setup express to serve static files (https://expressjs.com/en/starter/static-files.html) and finally in layout.js I would add

```
<link rel="stylesheet" href="my-css-file.css">
```

**Comment by richyrb00** [comment]
@wojtek-krysiak perfect, and works how i wanted it. thank you.
